### ISSUE TITLE
alternative names in glottolog-cldf?

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog-cldf#11]
Will alternative names of languoids ever be included in future glottolog-cldf releases? It could be either in the languages table or values.

**Comment by SamPassmore** [comment]
+1 I also came here to ask this question.

**Comment by xrotwang** [comment]
I think an additional table would be the best solution here, something like `names.csv`

Glottocode | Name | provider | lang
--- | --- | --- | ---
abcd1234 | Sprache | someone | de

**Comment by HedvigS** [comment]
Sure thing, sounds good to me. As long as it's in there somewhere :)
