### ISSUE TITLE
Add homeland coords for language groups ...

### ISSUE THREAD

**Issue by xrotwang** [glottolog/glottolog-cldf#14]
... computed as "minimal distance" as described in "Testing methods of linguistic homeland detection using synthetic data"
https://doi.org/10.1098/rstb.2020.0202

**Comment by xrotwang** [comment]
@d97hah This might be a useful addition as far as
- it adds geocoords for each family languoid
- it does so in a cheap yet principled way

Thoughts?

**Comment by xrotwang** [comment]
Implementation:
```python
"""
Testing methods of linguistic homeland detection using synthetic data
Søren Wichmann and Taraka Rama
https://doi.org/10.1098/rstb.2020.0202
"""
import random
import collections

import pyproj
from pycldf import Dataset


def geodist(geod, p1, p2):
    return geod.inv(p1[1], p1[0], p2[1], p2[0])[2]


def md(g, coords):
    if len(coords) == 1:
        return coords[0]
    if len(coords) == 2:
        return random.choice(coords)
    random.shuffle(coords)
    mindist, mincoord = None, None

    for i, coord in enumerate(coords):
        dist = sum(geodist(g, coord, p) for j, p in enumerate(coords) if i != j)
        if (mindist is None) or (dist < mindist):
            mindist, mincoord = dist, coord
    return mincoord


if __name__ == '__main__':
    cldf = Dataset.from_metadata('cldf/cldf-metadata.json')
    subgroups = collections.defaultdict(list)
    vals = [v for v in cldf['ValueTable'] if v['Parameter_ID'] in ['level', 'classification']]

    # Find language-level languoids with coordinates:
    languages = {
        v['Language_ID'] for v in vals
        if v['Parameter_ID'] == 'level' and v['Code_ID'] == 'level-language'}
    languages_with_coords = {
        l['ID']: (l['Latitude'], l['Longitude'])
        for l in cldf['LanguageTable'] if l['ID'] in languages and l['Latitude'] is not None}
    names = {l['ID']: l['Name'] for l in cldf['LanguageTable']}

    # Collect sets of languages per language family/subgroup:
    for v in vals:
        if (v['Language_ID'] in languages_with_coords) and (v['Parameter_ID'] == 'classification'):
            clf = v['Value'].split('/')
            for i, _ in enumerate(clf, start=1):
                subgroups[' '.join(clf[:i])].append(languages_with_coords[v['Language_ID']])

    # Compute minimal distances per group:
    g = pyproj.Geod(ellps='WGS84')
    for group, coords in sorted(subgroups.items(), key=lambda i: ','.join(names[gc] for gc in i[0].split())):
        print('{}\t{}\t{}\t{}'.format(*[','.join(names[gc] for gc in group.split())] + list(md(g, coords)) + [len(coords)]))
```

**Comment by d97hah** [comment]
The classic principle of max diversity seems to have these properties but
with better principles, i.e., in practice:

- The homeland of a family is the point with the shortest distance to the
(inferred) location of its immediate daughters (recursively)
- A cheap approximation to this is to take lat = avg([lat for (lat, lon) in
daughters]),  lon = avg([lon for (lat, lot) in daughters])
- If the resulting point is in water, take the nearest point on land to this

all the best,
H

Pada tanggal Kam, 13 Okt 2022 pukul 09.18 Robert Forkel <
***@***.***> menulis:

**Comment by xrotwang** [comment]
The "take the nearest point on land" bit seems non-trivial, though. The "minimal distance" approach gets around this in a somewhat crude way - but it comes with a citation to justify the approach :)

**Comment by xrotwang** [comment]
Arguably, though, having a coordinate for a language group on water, isn't completely non-sensical. It comes with the "the ancestors passed through here" connotation. 

Anyway, I think it wouldn't be a problem to add more ways to infer homelands lateron. (We'd like to get coordinates for proto-languages right now for Steve's bdproto - and the "minimal distance" ones would do the trick :) )

**Comment by xrotwang** [comment]
I'll try to whip up a "max diversity" algorithm accepting locations on water and plot the results.

**Comment by xrotwang** [comment]
Found a fairly simple (and amazingly fast) solution to the "nearest point on land" problem. Will send around results soon.

**Comment by d97hah** [comment]
Great, I have something similar implemented somewhere but you, as usual,
were faster! H

Pada tanggal Jum, 14 Okt 2022 pukul 09.53 Robert Forkel <
***@***.***> menulis:

**Comment by xrotwang** [comment]
My implementation is basically this:
```python
    from shapely.geometry import MultiPoint
    from shapely.ops import nearest_points

    cent = MultiPoint([(p[1] + 360 if p[1] < 0 else p[1], p[0]) for p in coords]).convex_hull.centroid
    homeland = nearest_points(land, cent)[0]
    return (homeland.y, homeland.x - 360 if homeland.x > 180 else homeland.x)
```
where `land` is the MultiPolygon from https://geojson-maps.ash.ms/

**Comment by xrotwang** [comment]
@d97hah to get rid of the weirdest effects of languages like Hunsrik, one could limit the eligible languages for homeland computation to certain combinations of macroareas. Do you think that makes sense? E.g. exclude the Americas whenever there's other macroareas involved?

**Comment by xrotwang** [comment]
Looking over the families, a simple blacklist of macroareas for Atlantic-Congo, Austronesian and Indo-European would probably be enough, though.

**Comment by xrotwang** [comment]
@d97hah do you have a citation for this method of computing homelands? It isn't exactly the "diversity" method presented in Wichmann 2015.

**Comment by xrotwang** [comment]
Wikipedia sees to cite [Campbell 2013](https://glottolog.org/resource/reference/id/547852) for this.

**Comment by d97hah** [comment]
It goes back to Sapir and there's also a botanical analogue by someone
called Vavrilov (?, from memory). Neither has the 'in water' twist. It's
enough to cite Campbell 2013 I think, which should contain refs to the
history.

Pada tanggal Jum, 14 Okt 2022 pukul 15.55 Robert Forkel <
***@***.***> menulis:

**Comment by xrotwang** [comment]
Ok, I'll update #15 to include these homelands.
