### ISSUE TITLE
timespan for next release

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog-cldf#20]
Could the glottolog languoid attribute "timespan" be included in future glottolog-cldf releases?

looks handy!

**Comment by HedvigS** [comment]
Hold on, Is "First_Year_Of_Documentation" and "Last_Year_Of_Documentation" in glottolog-cldf's LanguageTable the timespan information? Or is this another kind of time information separate from what Harald calls "timespan"?

**Comment by HedvigS** [comment]
I think they may be the same thing, the more I look at what I got from Harald and what's in the LangugeTable already. I didn't understand the description. First when I read "The first year that an extinct languoid was documented " I thought it was referring to publication dates rather than dates when the languoid was documented to be in use.

**Comment by xrotwang** [comment]
It is, see https://github.com/glottolog/glottolog-cldf/blob/776f818e68b31922d65a134b4642f88e4db06e94/cldfbench_glottolog.py#L222-L240

**Comment by HedvigS** [comment]
Alright, all good then. Now I know where to look.

**Comment by SimonGreenhill** [comment]
@HedvigS 

```r
g <- rgrambank::load_glottolog()
head(g$tables$LanguageTable[c("ID", "Name", "First_Year_Of_Documentation", "Last_Year_Of_Documentation")])

        ID            Name First_Year_Of_Documentation Last_Year_Of_Documentation
1 fuln1247          Fulniô                          NA                         NA
2 demm1245             Dem                          NA                         NA
3 mixe1284      Mixe-Zoque                          NA                         NA
4 mure1235            Mure                          NA                       1800
5 nort2923 North Halmahera                          NA                         NA
6 tonk1249         Tonkawa                          NA                       1965

```

**Comment by HedvigS** [comment]
> @HedvigS
> 
> ```r
> g <- rgrambank::load_glottolog()
> head(g$tables$LanguageTable[c("ID", "Name", "First_Year_Of_Documentation", "Last_Year_Of_Documentation")])
> 
>         ID            Name First_Year_Of_Documentation Last_Year_Of_Documentation
> 1 fuln1247          Fulniô                          NA                         NA
> 2 demm1245             Dem                          NA                         NA
> 3 mixe1284      Mixe-Zoque                          NA                         NA
> 4 mure1235            Mure                          NA                       1800
> 5 nort2923 North Halmahera                          NA                         NA
> 6 tonk1249         Tonkawa                          NA                       1965
> ```

Yep I found that later. I didn't know they were related, I was looking for the word "timespan" that I had seen Harald use. I hadn't noticed those columns before, but now I know :)
