### ISSUE TITLE
Agglomerated Endangerment Scale in CLDF?

### ISSUE THREAD

**Issue by SamPassmore** [glottolog/glottolog-cldf#22]
Hi Robert / other Glottologers, 

I am looking for the Agglomerated Endangerment Scale data listed on the Glottoscope part of Glottolog.org. Does this exist in the CLDF dataset and I am too lbind to see it? Or where could I find this data? 

TYIA,

Sam

**Comment by xrotwang** [comment]
It should be in there, see this recipe: https://github.com/glottolog/cookbook/blob/master/recipes/glottolog_cldf/documentation_status_for_subgroup.md

**Comment by xrotwang** [comment]
Ah, that was MED, but AES is in there as well, see https://github.com/cldf/cookbook/blob/master/recipes/cldf_r/README.md

**Comment by xrotwang** [comment]
Here's how you'd get at the AES data in CLDF SQL:
```sql
sqlite> select c.cldf_name, count(v.cldf_languageReference) from codetable as c, valuetable as v where v.cldf_parameterReference = 'aes' and v.cldf_codeReference = c.cldf_id group by c.cldf_name;
extinct|1248
moribund|410
nearly extinct|349
not endangered|2958
shifting|1830
threatened|1518
```

**Comment by SamPassmore** [comment]
Ok - perfect. Thanks, Robert.
