### ISSUE TITLE
Isolate dialects are also isolates

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog-cldf#24]
For future CLDF-releases of Glottolog, could dialects of isolates also be tagged as TRUE for "Is_isolate" in the LanguageTable?

Please and thank you.

**Comment by xrotwang** [comment]
Isn't "isolate" a property that only applies to languages? So tagging dialects as isolates could be misleading. E.g. right now you can count the number of isolates by counting rows in LanguageTable where "Is_Isolate" is True.

**Comment by xrotwang** [comment]
See also https://github.com/glottolog/glottolog/issues/1015#issuecomment-1695713132

**Comment by HedvigS** [comment]
I don't think it's misleading, but it seems like it's against yours, @xflr6  and @d97hah set-up so no worries. all good.
