### ISSUE TITLE
MED granularity?

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog-cldf#3]
I finally updated my R scripts that cobble together a table from the glottolog data in a format that I prefer ([here](https://github.com/HedvigS/Glottolog_look_up_table)). As I was shifting from a langouds.csv and treedb approach to using almost only the glottolog cldf I noticed a few smaller changes. It all went fine, I think i understood most of the decisions.

I was just curious, will the cldf release ever contain more fine-grained categories for "med" below wordlist?

**Comment by xrotwang** [comment]
"wordlist" is the "lowest" type in the [document types](https://glottolog.org/meta/glossary#Doctype) recognized by Glottolog. So providing more granularity "below" would only be possible, if the whole database would be annotated with new document types. I don't think this going to happen.

Why would you need this and which types would you suggest?

**Comment by HedvigS** [comment]
Right, okay. Will med ever include any more granularity, or is there another way of getting the old "doctype" from the cldf release?

I just found it a bit confusing to only work with these 5 med classes instead of the previous 16 doctypes. Is "specific_feature" lumped into med class "phonology/text" or "wordlist or less"? I take it "phonology/text" then if wordlist is the lowest?

**Comment by HedvigS** [comment]
Ah, right, Just found ["From highest to lowest, the ranking is grammar, grammar sketch, dictionary/phonology/specific feature/text, wordlist, followed by the remaining document types.".](https://glottolog.org/meta/glossary#sec-mostextensivedescriptionmed)

That means "phonology/text" includes "specific_feature". Right, okay.

**Comment by xrotwang** [comment]
Here's the code that computes `med_type`: https://github.com/glottolog/pyglottolog/blob/master/src/pyglottolog/references/bibfiles.py#L267-L278
and here's the doctypes: https://github.com/glottolog/glottolog/blob/master/config/document_types.ini
with ordering defined by `rank`.

**Comment by xrotwang** [comment]
So yes, [ethnographic work](https://github.com/glottolog/glottolog/blob/7970be034ba5e048d2e3ab744e302091f150a350/config/document_types.ini#L270-L273) is ranked 3, below [wordlist](https://github.com/glottolog/glottolog/blob/7970be034ba5e048d2e3ab744e302091f150a350/config/document_types.ini#L147-L150), ranked 10.

**Comment by xrotwang** [comment]
Getting the document type(s) for a MED from the CLDF release would work as follows:
1. You determine the BibTeX key of the MED, given in the `Source` column of the relevant row in `values.csv`, e.g. `hh:s:Crevels:Canichana` for `cani1243`, from
   ```csv
   cani1243-med,cani1243,med,grammar sketch,med-grammar_sketch,,hh:s:Crevels:Canichana,
   ```
2. You lookup the `hhtype` field of this reference in `sources.bib`:
   ```bibtex
   @incollection{hh:s:Crevels:Canichana,
       author = {Crevels, Mily},
       ...
       hhtype = {grammar_sketch},
       ...
       year = {2012}
   }
   ```

**Comment by HedvigS** [comment]
Okay, so specifically "wordlist" is not the lowest type and the more granular hhtype is retrievable. Thanks!

**Comment by xrotwang** [comment]
Ah, sorry, I was wrong saying "wordlist is the lowest type". Will make sure the order at https://glottolog.org/meta/glossary#Doctype is by rank and not alphabetical. See https://github.com/clld/glottolog3/issues/125

**Comment by HedvigS** [comment]
No worries, thanks :)!
